/*
 * OpenAI API
 * APIs for sampling from and fine-tuning language models
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.CreateModerationResponseCategories;
import io.swagger.client.model.CreateModerationResponseCategoryScores;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * CreateModerationResponseResults
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-07-22T11:54:28.282623982Z[GMT]")

public class CreateModerationResponseResults {
  @SerializedName("flagged")
  private Boolean flagged = null;

  @SerializedName("categories")
  private CreateModerationResponseCategories categories = null;

  @SerializedName("category_scores")
  private CreateModerationResponseCategoryScores categoryScores = null;

  public CreateModerationResponseResults flagged(Boolean flagged) {
    this.flagged = flagged;
    return this;
  }

   /**
   * Get flagged
   * @return flagged
  **/
  @Schema(required = true, description = "")
  public Boolean isFlagged() {
    return flagged;
  }

  public void setFlagged(Boolean flagged) {
    this.flagged = flagged;
  }

  public CreateModerationResponseResults categories(CreateModerationResponseCategories categories) {
    this.categories = categories;
    return this;
  }

   /**
   * Get categories
   * @return categories
  **/
  @Schema(required = true, description = "")
  public CreateModerationResponseCategories getCategories() {
    return categories;
  }

  public void setCategories(CreateModerationResponseCategories categories) {
    this.categories = categories;
  }

  public CreateModerationResponseResults categoryScores(CreateModerationResponseCategoryScores categoryScores) {
    this.categoryScores = categoryScores;
    return this;
  }

   /**
   * Get categoryScores
   * @return categoryScores
  **/
  @Schema(required = true, description = "")
  public CreateModerationResponseCategoryScores getCategoryScores() {
    return categoryScores;
  }

  public void setCategoryScores(CreateModerationResponseCategoryScores categoryScores) {
    this.categoryScores = categoryScores;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateModerationResponseResults createModerationResponseResults = (CreateModerationResponseResults) o;
    return Objects.equals(this.flagged, createModerationResponseResults.flagged) &&
        Objects.equals(this.categories, createModerationResponseResults.categories) &&
        Objects.equals(this.categoryScores, createModerationResponseResults.categoryScores);
  }

  @Override
  public int hashCode() {
    return Objects.hash(flagged, categories, categoryScores);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateModerationResponseResults {\n");
    
    sb.append("    flagged: ").append(toIndentedString(flagged)).append("\n");
    sb.append("    categories: ").append(toIndentedString(categories)).append("\n");
    sb.append("    categoryScores: ").append(toIndentedString(categoryScores)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
