/*
 * OpenAI API
 * APIs for sampling from and fine-tuning language models
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.math.BigDecimal;
/**
 * CreateModerationResponseCategoryScores
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-07-22T11:54:28.282623982Z[GMT]")

public class CreateModerationResponseCategoryScores {
  @SerializedName("hate")
  private BigDecimal hate = null;

  @SerializedName("hate/threatening")
  private BigDecimal hatethreatening = null;

  @SerializedName("self-harm")
  private BigDecimal selfHarm = null;

  @SerializedName("sexual")
  private BigDecimal sexual = null;

  @SerializedName("sexual/minors")
  private BigDecimal sexualminors = null;

  @SerializedName("violence")
  private BigDecimal violence = null;

  @SerializedName("violence/graphic")
  private BigDecimal violencegraphic = null;

  public CreateModerationResponseCategoryScores hate(BigDecimal hate) {
    this.hate = hate;
    return this;
  }

   /**
   * Get hate
   * @return hate
  **/
  @Schema(required = true, description = "")
  public BigDecimal getHate() {
    return hate;
  }

  public void setHate(BigDecimal hate) {
    this.hate = hate;
  }

  public CreateModerationResponseCategoryScores hatethreatening(BigDecimal hatethreatening) {
    this.hatethreatening = hatethreatening;
    return this;
  }

   /**
   * Get hatethreatening
   * @return hatethreatening
  **/
  @Schema(required = true, description = "")
  public BigDecimal getHatethreatening() {
    return hatethreatening;
  }

  public void setHatethreatening(BigDecimal hatethreatening) {
    this.hatethreatening = hatethreatening;
  }

  public CreateModerationResponseCategoryScores selfHarm(BigDecimal selfHarm) {
    this.selfHarm = selfHarm;
    return this;
  }

   /**
   * Get selfHarm
   * @return selfHarm
  **/
  @Schema(required = true, description = "")
  public BigDecimal getSelfHarm() {
    return selfHarm;
  }

  public void setSelfHarm(BigDecimal selfHarm) {
    this.selfHarm = selfHarm;
  }

  public CreateModerationResponseCategoryScores sexual(BigDecimal sexual) {
    this.sexual = sexual;
    return this;
  }

   /**
   * Get sexual
   * @return sexual
  **/
  @Schema(required = true, description = "")
  public BigDecimal getSexual() {
    return sexual;
  }

  public void setSexual(BigDecimal sexual) {
    this.sexual = sexual;
  }

  public CreateModerationResponseCategoryScores sexualminors(BigDecimal sexualminors) {
    this.sexualminors = sexualminors;
    return this;
  }

   /**
   * Get sexualminors
   * @return sexualminors
  **/
  @Schema(required = true, description = "")
  public BigDecimal getSexualminors() {
    return sexualminors;
  }

  public void setSexualminors(BigDecimal sexualminors) {
    this.sexualminors = sexualminors;
  }

  public CreateModerationResponseCategoryScores violence(BigDecimal violence) {
    this.violence = violence;
    return this;
  }

   /**
   * Get violence
   * @return violence
  **/
  @Schema(required = true, description = "")
  public BigDecimal getViolence() {
    return violence;
  }

  public void setViolence(BigDecimal violence) {
    this.violence = violence;
  }

  public CreateModerationResponseCategoryScores violencegraphic(BigDecimal violencegraphic) {
    this.violencegraphic = violencegraphic;
    return this;
  }

   /**
   * Get violencegraphic
   * @return violencegraphic
  **/
  @Schema(required = true, description = "")
  public BigDecimal getViolencegraphic() {
    return violencegraphic;
  }

  public void setViolencegraphic(BigDecimal violencegraphic) {
    this.violencegraphic = violencegraphic;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateModerationResponseCategoryScores createModerationResponseCategoryScores = (CreateModerationResponseCategoryScores) o;
    return Objects.equals(this.hate, createModerationResponseCategoryScores.hate) &&
        Objects.equals(this.hatethreatening, createModerationResponseCategoryScores.hatethreatening) &&
        Objects.equals(this.selfHarm, createModerationResponseCategoryScores.selfHarm) &&
        Objects.equals(this.sexual, createModerationResponseCategoryScores.sexual) &&
        Objects.equals(this.sexualminors, createModerationResponseCategoryScores.sexualminors) &&
        Objects.equals(this.violence, createModerationResponseCategoryScores.violence) &&
        Objects.equals(this.violencegraphic, createModerationResponseCategoryScores.violencegraphic);
  }

  @Override
  public int hashCode() {
    return Objects.hash(hate, hatethreatening, selfHarm, sexual, sexualminors, violence, violencegraphic);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateModerationResponseCategoryScores {\n");
    
    sb.append("    hate: ").append(toIndentedString(hate)).append("\n");
    sb.append("    hatethreatening: ").append(toIndentedString(hatethreatening)).append("\n");
    sb.append("    selfHarm: ").append(toIndentedString(selfHarm)).append("\n");
    sb.append("    sexual: ").append(toIndentedString(sexual)).append("\n");
    sb.append("    sexualminors: ").append(toIndentedString(sexualminors)).append("\n");
    sb.append("    violence: ").append(toIndentedString(violence)).append("\n");
    sb.append("    violencegraphic: ").append(toIndentedString(violencegraphic)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
